/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        // ── shadcn HSL slots (Button only) ──
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },

        // ── Semantic (default consumption layer) ──
        "surface-page":       "var(--surface-page)",
        "surface-raised":     "var(--surface-raised)",
        "surface-subtle":     "var(--surface-subtle)",
        "surface-strong":     "var(--surface-strong)",
        "text-primary":       "var(--text-primary)",
        "text-secondary":     "var(--text-secondary)",
        "text-tertiary":      "var(--text-tertiary)",
        "text-inverse":       "var(--text-inverse)",
        "text-accent":        "var(--text-accent)",
        "icon-primary":       "var(--icon-primary)",
        "icon-secondary":     "var(--icon-secondary)",
        "icon-tertiary":      "var(--icon-tertiary)",
        "border-default":     "var(--border-default)",
        "border-strong":      "var(--border-strong)",
        "border-accent":      "var(--border-accent)",
        "accent-default":     "var(--accent-default)",
        "accent-hover":       "var(--accent-hover)",
        "accent-soft":        "var(--accent-soft)",
        "text-on-accent":     "var(--text-on-accent)",
        "status-success":      "var(--status-success)",
        "status-success-soft": "var(--status-success-soft)",
        "status-danger":       "var(--status-danger)",
        "status-danger-soft":  "var(--status-danger-soft)",
        "status-warning":      "var(--status-warning)",
        "status-warning-soft": "var(--status-warning-soft)",

        // ── Component slots (use when retuning one component) ──
        "btn-primary-bg":        "var(--btn-primary-bg)",
        "btn-primary-bg-hover":  "var(--btn-primary-bg-hover)",
        "btn-primary-fg":        "var(--btn-primary-fg)",
        "btn-secondary-bg":      "var(--btn-secondary-bg)",
        "btn-secondary-bg-hover":"var(--btn-secondary-bg-hover)",
        "btn-secondary-fg":      "var(--btn-secondary-fg)",
        "btn-secondary-border":  "var(--btn-secondary-border)",
        "tabbar-active-label":   "var(--tabbar-active-label)",
        "tabbar-active-icon":    "var(--tabbar-active-icon)",
        "tabbar-inactive-label": "var(--tabbar-inactive-label)",
        "tabbar-inactive-icon":  "var(--tabbar-inactive-icon)",
        "card-bg":               "var(--card-bg)",
        "card-border":           "var(--card-border)",
        "card-question-bg":      "var(--card-question-bg)",
        "card-question-bar":     "var(--card-question-bar)",
        "card-tag-bg":           "var(--card-tag-bg)",
        "option-bg":             "var(--option-bg)",
        "chip-bg":               "var(--chip-bg)",
        "chip-bg-active":        "var(--chip-bg-active)",
        "chip-border-active":    "var(--chip-border-active)",
        "chip-icon-bg":          "var(--chip-icon-bg)",
        "chip-icon-fg":          "var(--chip-icon-fg)",
        "pagination-track":      "var(--pagination-track)",
        "pagination-fill":       "var(--pagination-fill)",
        "avatar-bg":             "var(--avatar-bg)",
        "avatar-bg-success":     "var(--avatar-bg-success)",
        "avatar-bg-alert":       "var(--avatar-bg-alert)",
        "page-feed":             "var(--page-bg-feed)",
        "app-header":            "var(--app-header-bg)",
        "app-header-fg":         "var(--app-header-fg)",
        "app-header-muted":      "var(--app-header-muted)",
        "app-header-field":      "var(--app-header-field-bg)",
        "app-header-field-hover":"var(--app-header-field-bg-hover)",
        "app-header-border":     "var(--app-header-border)",
        "app-content":           "var(--app-content-bg)",
        "topbar":                "var(--topbar-bg)",
        "topbar-fg":             "var(--topbar-fg)",
        "topbar-muted":          "var(--topbar-muted)",
        "topbar-field":          "var(--topbar-field-bg)",
        "topbar-field-hover":    "var(--topbar-field-bg-hover)",
        "cal-campaign":          "var(--cal-campaign-bg)",
        "cal-campaign-fg":       "var(--cal-campaign-fg)",
        "cal-polst":             "var(--cal-polst-bg)",
        "cal-polst-fg":          "var(--cal-polst-fg)",
        "cal-event-dot":         "var(--cal-event-dot)",
        "tabchip-bg":            "var(--tabchip-bg)",
        "tabchip-bg-active":     "var(--tabchip-bg-active)",
        "tabchip-fg":            "var(--tabchip-fg)",
        "tabchip-icon-active":   "var(--tabchip-icon-active)",

        // ── Primitives (escape hatch, prefer semantics) ──
        "neutral-50":  "var(--color-neutral-50)",
        "neutral-100": "var(--color-neutral-100)",
        "neutral-150": "var(--color-neutral-150)",
        "neutral-200": "var(--color-neutral-200)",
        "neutral-250": "var(--color-neutral-250)",
        "neutral-300": "var(--color-neutral-300)",
        "neutral-400": "var(--color-neutral-400)",
        "neutral-500": "var(--color-neutral-500)",
        "neutral-600": "var(--color-neutral-600)",
        "neutral-700": "var(--color-neutral-700)",
        "neutral-800": "var(--color-neutral-800)",
        "neutral-900": "var(--color-neutral-900)",
        "ink-purple":   "var(--color-ink-purple)",
        "brand-purple": "var(--color-brand-purple)",
        "soft-purple":  "var(--color-soft-purple)",
        "base-red":     "var(--color-red)",
        "base-yellow":  "var(--color-yellow)",
        "base-green":   "var(--color-green)",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        // Inter everywhere — `font-display` kept as a semantic alias, no Inter Tight.
        display: ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        // Unified control type — buttons, tabs, selectors, nav, menu rows.
        ui: ["13px", "16px"],
      },
      maxWidth: {
        // ONE content container: every page — Home board, data tables,
        // editors — caps at the same width so the app reads as one system.
        dashboard: "1200px",
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        card: "var(--radius-card)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
        pill: "var(--radius-pill)",
      },
      boxShadow: {
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        pop: "var(--shadow-pop)",
      },
      transitionTimingFunction: {
        // Fast departure settling into a long glide — no overshoot.
        slide: "cubic-bezier(0.22, 1, 0.36, 1)",
      },
    },
  },
  plugins: [],
};
